title: Changing Gears
description: Transitioning into early retirement, travel, and new adventures.
baseurl: ""
url: "https://changing-gears.com"
permalink: /:title/
excerpt_separator: "<!--more-->"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
